# Generated by Django 5.1.4 on 2025-01-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_options_subs"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="amount",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Сумма оплаты курса или урока"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Id сессии"
            ),
        ),
    ]
