version: '3.9'

services:
  web:
    container_name: app_django_treatise
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file:
        - .env

  redis:
    container_name: redis
    image: redis:6

  celery:
    container_name: celery
    build: .
    command: >
      bash -c "celery -A config.celery  worker --loglevel=INFO -B"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery_beat:
    container_name: celery_beat
    build: .
    env_file:
      - .env
    command: >
      bash -c "celery -A config beat --loglevel=info"
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume: