# Generated by Django 5.1.4 on 2024-12-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Treatise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название курса",
                        max_length=100,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatise/photo"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Введите описание курса"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урок",
                        max_length=100,
                        verbose_name="Урок",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lesson/photo"),
                ),
                (
                    "link_to_video",
                    models.CharField(
                        help_text="Введите ссылку на урок",
                        max_length=200,
                        verbose_name="Ссылка",
                    ),
                ),
                (
                    "treatise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.treatise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "ordering": ["treatise", "name"],
            },
        ),
    ]
