# Generated by Django 5.1.4 on 2025-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_lesson_owner_treatise_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatise",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
