# Generated by Django 5.1.4 on 2025-01-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_treatise_is_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_video",
            field=models.CharField(
                blank=True,
                help_text="Введите ссылку на урок",
                max_length=200,
                null=True,
                verbose_name="Ссылка",
            ),
        ),
    ]
