# Generated by Django 5.1.4 on 2025-01-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_link_to_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatise",
            name="is_subscribed",
        ),
    ]
